orb_breakout:
  best_params:
    orb_minutes: 43
  best_value: 500.8164
  metric: sortino
  strategy: orb_breakout
vwap_pullback:
  best_params:
    atr_mult: 1.3200362845189182
    tolerance_pct: 0.1157028165267155
  best_value: 265839605.5249
  metric: sortino
  strategy: vwap_pullback
